config/routes.rb
Formbuilder::Application.routes.draw do
  resources :results, only: [:create]

  resources :forms

  root to: 'forms#index'

end

app/models/form.rb
class Form < ActiveRecord::Base
	has_many :results
end

app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :form
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with :name => "formadmin", :password => "ololo"
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render action: 'show', status: :created, location: @form }
      else
        format.html { render action: 'new' }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      # params[:form][:body]
      params.require(:form).permit(:body, :title)
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]
  before_action :set_form

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    respond_to do |format|
      if @form.results.create(body: result_params.to_json)
        format.html { redirect_to @form, notice: 'Result was successfully created.' }
        format.json { render action: 'show', status: :created, location: @result }
      else
        format.html { render action: 'new' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    def set_form
      @form = Form.find(params[:form_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      # params.except(:controller, :action, :commit, :utf8, :authenticity_token).to_json
      params.require(:result).permit!
      # params.except(:controller, :action, :commit, :utf8, :authenticity_token).to_json
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/forms/_form.html.erb
<div id="stage">
    <dix id="menu">
      <div class="tabbable tabs-left">
        <ul class="nav nav-tabs">
          <li class=""><a href="#A" data-toggle="tab">Header</a></li>
          <li class=""><a href="#B" data-toggle="tab">Color</a></li>
          <li class=""><a href="#C" data-toggle="tab">TextLine</a></li>
          <li class=""><a href="#D" data-toggle="tab">TextArea</a></li>
          <li class=""><a href="#E" data-toggle="tab">Radio</a></li>
          <li class=""><a href="#F" data-toggle="tab">Select</a></li>
          <li class=""><a href="#G" data-toggle="tab">Fancy Pants</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active">
            <p>
              <h2 style="color: gainsboro;">Wanna build some form?</h2>
              <h3 style="color: gainsboro;"> Choose tabs left </h3>
            </p>
          </div>
          <div class="tab-pane" id="A">
            <p>
              <input id="header_input" type="text" placeholder="Enter form header">
              <input id="header_color" type="text" placeholder="Enter header bg color">
              <input type="range" min="10" max="80" step="5" value="50" id="header_size"> 
            </p>
          </div>
          <div class="tab-pane" id="B">
            <p><input id="bg_color_input" type="text" placeholder="main background color"></p>
            <p><input id="inp_color_input" type="text" placeholder="inputs background color"></p>
          </div>
          <div class="tab-pane" id="C">
            <p>
              <input type="text" placeholder="Enter label">
              <input type="range" min="100" max="400" step="20" value="206" id="line_size"> 
              <%= link_to "Add simple input", "", id: :line_add, remote: true, class: "btn" %>
              <!-- <input type="radio" name="browser" value="ie"> Left
              <input type="radio" name="browser" value="opera"> Right -->
            </p>
          </div>
          <div class="tab-pane" id="D">
            <p>
              <input type="text" placeholder="Enter label">
              <%= link_to "Add text area", "", id: :text_add, remote: true, class: "btn" %>
            </p>
          </div>
          <div class="tab-pane" id="E">
            <p>
              <input type="text" placeholder="Enter label" id="label">
              <input type="text" placeholder="list of options separated by whitespace" id="radioptions">
              <%= link_to "Add radio group", "", id: :radio_add, remote: true, class: "btn" %>
            </p>
          </div>
          <div class="tab-pane" id="F">
            <p>
              <input type="text" placeholder="Enter label" id="label"> 
              <input type="text" size="50" id="options" placeholder="list of options separated by whitespace">
              <%= link_to "Add selectbox", "", id: :select_add, remote: true, class: "btn" %>
            </p>
          </div>
          <div class="tab-pane" id="G">
            <p>
              <%= link_to "Add separator", "", id: :hr_add, remote: true, class: "btn" %> 
              <!-- <input type="text" size="50" placeholder="list of options separated by whitespace"> -->
            </p>
          </div>
        </div>
      </div>

      
      
      
      <p>
        <%= link_to "Clear form", "", id: :clear, remote: true, class: "btn btn-danger" %> 
        <!-- <input type="text" size="50" placeholder="list of options separated by whitespace"> -->
      </p>
    </dix>
    <dix id="main">
      <h2 id="header"></h2>
      <ul id="sortable">
      </ul>
    </dix>
  </div>

<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_area :body %>
  <%= f.hidden_field :title %>

  <div class="actions">
    <%= f.submit "Create form", class: "btn" %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing form</h1>

<div id="stage">
    <dix id="menu">
      <div class="tabbable tabs-left">
        <ul class="nav nav-tabs">
          <li class=""><a href="#A" data-toggle="tab">Header</a></li>
          <li class=""><a href="#B" data-toggle="tab">Color</a></li>
          <li class=""><a href="#C" data-toggle="tab">TextLine</a></li>
          <li class=""><a href="#D" data-toggle="tab">TextArea</a></li>
          <li class=""><a href="#E" data-toggle="tab">Radio</a></li>
          <li class=""><a href="#F" data-toggle="tab">Select</a></li>
          <li class=""><a href="#G" data-toggle="tab">Fancy Pants</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active">
            <p>
              <h2 style="color: gainsboro;">Reorder fields</h2>
              <h3 style="color: gainsboro;"> Add new ones </h3>
            </p>
          </div>
          <div class="tab-pane" id="A">
            <p>
              <input id="header_input" type="text" placeholder="Enter form header">
              <input id="header_color" type="text" placeholder="Enter header bg color">
              <input type="range" min="10" max="80" step="5" value="50" id="header_size"> 
            </p>
          </div>
          <div class="tab-pane" id="B">
            <p><input id="bg_color_input" type="text" placeholder="main background color"></p>
            <p><input id="inp_color_input" type="text" placeholder="inputs background color"></p>
          </div>
          <div class="tab-pane" id="C">
            <p>
              <input type="text" placeholder="Enter label">
              <input type="range" min="100" max="400" step="20" value="206" id="line_size"> 
              <%= link_to "Add simple input", "", id: :line_add, remote: true, class: "btn" %>
              <!-- <input type="radio" name="browser" value="ie"> Left
              <input type="radio" name="browser" value="opera"> Right -->
            </p>
          </div>
          <div class="tab-pane" id="D">
            <p>
              <input type="text" placeholder="Enter label">
              <%= link_to "Add text area", "", id: :text_add, remote: true, class: "btn" %>
            </p>
          </div>
          <div class="tab-pane" id="E">
            <p>
              <input type="text" placeholder="Enter label" id="label">
              <input type="text" placeholder="list of options separated by whitespace" id="radioptions">
              <%= link_to "Add radio group", "", id: :radio_add, remote: true, class: "btn" %>
            </p>
          </div>
          <div class="tab-pane" id="F">
            <p>
              <input type="text" placeholder="Enter label" id="label"> 
              <input type="text" size="50" id="options" placeholder="list of options separated by whitespace">
              <%= link_to "Add selectbox", "", id: :select_add, remote: true, class: "btn" %>
            </p>
          </div>
          <div class="tab-pane" id="G">
            <p>
              <%= link_to "Add separator", "", id: :hr_add, remote: true, class: "btn" %> 
              <!-- <input type="text" size="50" placeholder="list of options separated by whitespace"> -->
            </p>
          </div>
        </div>
      </div>

      
      
      
      <p>
        <%= link_to "Clear form", "", id: :clear, remote: true, class: "btn btn-danger" %> 
        <!-- <input type="text" size="50" placeholder="list of options separated by whitespace"> -->
      </p>
    </dix>
    <dix id="main">
      <%= @form.body.html_safe %>
      </ul>
    </dix>
  </div>

<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_area :body %>
  <%= f.hidden_field :title %>
  <p>Code</p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<h1>Listing forms</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.title %></td>
        <td><%= link_to 'Try', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path, class: "btn" %>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_for @form.results.build do |f| %> 
	<%= @form.body.html_safe%>
	<%= hidden_field_tag :form_id, @form.id %>
	<div class="actions">
    <%= f.submit %>
  </div>
<%end%>
<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>

<script>$("#sortable").sortable(); $( "#sortable" ).sortable('disable');</script>
<h3>Tiny results table:</h3>
<table>
  <thead>
  	<% unless @form.results.first.body.empty? %>
	    <tr>
	  		<% JSON.parse(@form.results.first.body).each do |key, value|%>
			    <th><%= key %></th>
		    <% end %> 
	    </tr>
    <%end%>
  </thead>

  <tbody>
    <% @form.results.each do |result| %>
      <tr>
      	<% unless result.body.empty? %>
	      	<% JSON.parse(result.body).each do |key, value|%>
				    <td><%= value %></td>
			    <% end %>
			  <%end%>
		  </tr>
    <% end %>
  </tbody>
</table>

app/views/forms/show.js.erb
  function disable() { 
    $( "#sortable" ).sortable('disable');
  };

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formbuilder</title>
	<%= stylesheet_link_tag  "application", media: :all %>
	<%= javascript_include_tag  "application" %>
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :form_id %><br>
    <%= f.text_field :form_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <thead>
    <tr>
      <th>Form</th>
      <th>Integer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.form_id %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Form:</strong>
  <%= @result.form_id %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>